[package]
name = "change"
version = "0.1.0"
edition = "2021"

[dependencies]
character_converter = "2.1.5"
async-fs = "2.1.2"
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }
futures-lite = "2.6.0"